### ISSUE TITLE
vivo系统崩溃，可以来研究一下

### ISSUE THREAD

**Issue by ysy950803** [Petterpx/FloatingX#170]
**你的Fx版本是多少**

最新版

**遇到了什么问题**

```
android.view.InflateException: Binary XML file line #18 in android:layout/floating_popup_overflow_button: Binary XML file line #18 in android:layout/floating_popup_overflow_button: Error inflating class ImageButton
Caused by: android.view.InflateException: Binary XML file line #18 in android:layout/floating_popup_overflow_button: Error inflating class ImageButton
Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable$LayerState cannot be cast to android.graphics.drawable.VivoListViewSelectorDrawable$ListViewSelectorState
	at android.graphics.drawable.VivoListViewSelectorDrawable.mutate(VivoListViewSelectorDrawable.java:280)
	at android.view.View.applyBackgroundTint(View.java:26054)
	at android.view.View.setBackgroundTintList(View.java:25956)
	at a0.L.q(SourceFile:1)
	at v.s.e(SourceFile:90)
	at v.A.<init>(SourceFile:24)
	at p.F.onCreateView(SourceFile:14)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1126)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1062)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:681)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:552)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at com.android.internal.widget.FtSlidePanelLayout.createRightButton(FtSlidePanelLayout.java:1105)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:222)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:186)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:182)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:178)
	at com.android.internal.widget.floatingtoolbar.VivoLocalFloatingToolbarPopup.createSlidePanel(VivoLocalFloatingToolbarPopup.java:1311)
	at com.android.internal.widget.floatingtoolbar.VivoLocalFloatingToolbarPopup.<init>(VivoLocalFloatingToolbarPopup.java:300)
	at com.vivo.VivoSystemFrameworkFactoryImpl.createVivoLocalFloatingToolbarPopup(VivoSystemFrameworkFactoryImpl.java:744)
	at com.android.internal.widget.floatingtoolbar.FloatingToolbarPopup.createVivoInstance(FloatingToolbarPopup.java:114)
	at com.android.internal.widget.floatingtoolbar.FloatingToolbarPopup.createInstance(FloatingToolbarPopup.java:105)
	at com.android.internal.widget.floatingtoolbar.FloatingToolbar.<init>(FloatingToolbar.java:121)
	at com.android.internal.policy.DecorView.createFloatingActionMode(DecorView.java:2451)
	at com.android.internal.policy.DecorView.createActionMode(DecorView.java:2300)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1172)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:1129)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1059)
	at android.view.View.startActionMode(View.java:7985)
	at android.widget.Editor.startInsertionActionMode(Editor.java:2724)
	at android.widget.Editor.toggleInsertionActionMode(Editor.java:1720)
	at android.widget.Editor.onTouchUpEvent(Editor.java:3008)
	at android.widget.TextView.onTouchEvent(TextView.java:13785)
	at android.view.View.dispatchTouchEvent(View.java:15890)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:690)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:2020)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1033)
	at p.z.dispatchTouchEvent(SourceFile:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:639)
	at android.view.View.dispatchPointerEvent(View.java:16174)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7953)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7075)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7142)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7103)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7276)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7111)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7333)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7079)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7142)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7103)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7111)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7079)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10411)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10362)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10323)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10575)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:286)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:176)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
```

**可复现的示例代码 或者 复现步骤**

vivo又魔改了什么东西吗？机型版本：V2118A，Android 14

**Comment by Petterpx** [comment]
注意这段：

**Comment by ysy950803** [comment]
> 注意这段： Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable$LayerState cannot be cast to android.graphics.drawable.VivoListViewSelectorDrawable$ListViewSelectorState at android.graphics.drawable.VivoListViewSelectorDrawable.mutate(VivoListViewSelectorDrawable.java:280) 明显是vivo自己自定义导致，改的话，看看 从 mutate() 这里能不能下手

vivo这样搞的话，会不会影响范围太大啦！作者有什么好的解决办法吗？

**Comment by Petterpx** [comment]
> > 注意这段： Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable$LayerState cannot be cast to android.graphics.drawable.VivoListViewSelectorDrawable$ListViewSelectorState at android.graphics.drawable.VivoListViewSelectorDrawable.mutate(VivoListViewSelectorDrawable.java:280) 明显是vivo自己自定义导致，改的话，看看 从 mutate() 这里能不能下手
> 
> vivo这样搞的话，会不会影响范围太大啦！作者有什么好的解决办法吗？
试试改一下你的drawable，就是xml里用到的drawable描述文件，不要使用selector，改为手动更改状态更改drawable呢

**Comment by Petterpx** [comment]
> > 注意这段： Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable$LayerState cannot be cast to android.graphics.drawable.VivoListViewSelectorDrawable$ListViewSelectorState at android.graphics.drawable.VivoListViewSelectorDrawable.mutate(VivoListViewSelectorDrawable.java:280) 明显是vivo自己自定义导致，改的话，看看 从 mutate() 这里能不能下手
> 
> vivo这样搞的话，会不会影响范围太大啦！作者有什么好的解决办法吗？

试试改一下你的drawable，就是xml里用到的drawable描述文件，不要使用selector，改为手动更改状态更改drawable呢

**Comment by Petterpx** [comment]
非fx问题，先关了
