### ISSUE TITLE
Android 5.1 系统悬浮窗报错 StackOverflowError

### ISSUE THREAD

**Issue by Orienser** [Petterpx/FloatingX#174]
**你的Fx版本是多少**
2.2.4

**遇到了什么问题**
在 Android 5.1 的机型上使用系统悬浮窗模式显示时，报错StackOverflowError。

**可复现的示例代码 或者 复现步骤**
1. `AndroidManifest.xml`中声明权限：
```
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
<uses-permission android:name="android.permission.SYSTEM_OVERLAY_WINDOW" />
```
2. `MainActivity#onCreate`中显示浮窗：
```
FloatingX.install(FxAppHelper.builder()
                .setContext(this)
                .setScopeType(FxScopeType.SYSTEM)
                .build())
        .show();
```
3. 报错：
```
Thread: Thread[main,5,main]
java.lang.StackOverflowError: stack size 8MB
	at com.petterp.floatingx.util._FxExt.getTopActivity(FxExt.kt:39)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.checkOrInit(FxSystemPlatformProvider.kt:62)
	at com.petterp.floatingx.imp.FxBasisControlImp.updateEnableStatusAndCheckCanShow(FxBasisControlImp.kt:58)
	at com.petterp.floatingx.imp.FxBasisControlImp.show(FxBasisControlImp.kt:45)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.internalAskAutoPermission$floatingx_release(FxSystemPlatformProvider.kt:145)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.checkOrInit(FxSystemPlatformProvider.kt:70)
	at com.petterp.floatingx.imp.FxBasisControlImp.updateEnableStatusAndCheckCanShow(FxBasisControlImp.kt:58)
	at com.petterp.floatingx.imp.FxBasisControlImp.show(FxBasisControlImp.kt:45)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.internalAskAutoPermission$floatingx_release(FxSystemPlatformProvider.kt:145)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.checkOrInit(FxSystemPlatformProvider.kt:70)
	at com.petterp.floatingx.imp.FxBasisControlImp.updateEnableStatusAndCheckCanShow(FxBasisControlImp.kt:58)
	at com.petterp.floatingx.imp.FxBasisControlImp.show(FxBasisControlImp.kt:45)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.internalAskAutoPermission$floatingx_release(FxSystemPlatformProvider.kt:145)
	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.checkOrInit(FxSystemPlatformProvider.kt:70)
	at com.petterp.floatingx.imp.FxBasisControlImp.updateEnableStatusAndCheckCanShow(FxBasisControlImp.kt:58)
	at com.petterp.floatingx.imp.FxBasisControlImp.show(FxBasisControlImp.kt:45)
...
```
**报错原因**
推测问题可能出在`FxSystemPlatformProvider#checkAgreePermission`和`FxSystemPlatformProvider#internalAskAutoPermission`对安卓6.0以下设备的权限判断，导致这类设备会在`FxSystemPlatformProvider#internalAskAutoPermission`中循环调用`FxBasisControlImp#show`。

**Comment by Petterpx** [comment]
感谢反馈，晚些时候修复

**Comment by Petterpx** [comment]
更新到2.2.5 即可。
