### ISSUE TITLE
自动吸附时使用FloatingX.controlOrNull()?.cancel() 时崩溃

### ISSUE THREAD

**Issue by vztnfefscur224** [Petterpx/FloatingX#175]
**你的Fx版本是多少**
2.2.4
**遇到了什么问题**
自动吸附时调用FloatingX.controlOrNull()?.cancel() 时崩溃
**可复现的示例代码 或者 复现步骤**
```
java.lang.IllegalArgumentException: View=com.petterp.floatingx.view.FxSystemContainerView{b18ec10 G.E...... ......ID 0,0-182,182} not attached to window manager
                                                                                                    	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
                                                                                                    	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:380)
                                                                                                    	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:99)
                                                                                                    	at com.petterp.floatingx.view.FxSystemContainerView.updateXY(FxSystemContainerView.kt:87)
                                                                                                    	at com.petterp.floatingx.view.helper.FxViewAnimationHelper.checkOrInitAnimator$lambda-1$lambda-0(FxViewAnimationHelper.kt:38)
                                                                                                    	at com.petterp.floatingx.view.helper.FxViewAnimationHelper.$r8$lambda$XEyTq2nKk8Wsj0Cih0DjpftQ6WU(Unknown Source:0)
                                                                                                    	at com.petterp.floatingx.view.helper.FxViewAnimationHelper$$ExternalSyntheticLambda0.onAnimationUpdate(D8$$SyntheticClass:0)
                                                                                                    	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
                                                                                                    	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
                                                                                                    	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
                                                                                                    	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
                                                                                                    	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
                                                                                                    	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:693)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6840)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

拖动到中间，在onUp方法中使用FloatingX.controlOrNull()?.cancel()

**Comment by Petterpx** [comment]
感谢反馈，晚些时候处理

**Comment by Petterpx** [comment]
更新到2.2.5 即可。
