### ISSUE TITLE
跳转黑名单页面的时候调用uninstallAll有概率崩溃

### ISSUE THREAD

**Issue by StephoneWong** [Petterpx/FloatingX#181]
**你的Fx版本是多少**
v2.2.4

**遇到了什么问题**
跳转黑名单页面的时候调用uninstallAll有概率崩溃

java.lang.NullPointerException: Attempt to write to field 'android.view.ViewParent android.view.View.mParent' on a null object reference in method 'void android.view.ViewGroup.removeFromArray(int)'
	at android.view.ViewGroup.removeFromArray(ViewGroup.java:5402)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5599)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5561)
	at android.view.ViewGroup.removeView(ViewGroup.java:5492)
	at com.petterp.floatingx.imp.app.FxAppPlatformProvider.detach(FxAppPlatformProvider.kt:140)
	at com.petterp.floatingx.imp.app.FxAppPlatformProvider.hide(FxAppPlatformProvider.kt:82)
	at com.petterp.floatingx.imp.app.FxAppPlatformProvider.reset(FxAppPlatformProvider.kt:129)
	at com.petterp.floatingx.imp.FxBasisControlImp.reset(FxBasisControlImp.kt:153)
	at com.petterp.floatingx.imp.app.FxAppControlImp.reset(FxAppControlImp.kt:46)
	at com.petterp.floatingx.imp.FxBasisControlImp.cancel(FxBasisControlImp.kt:85)
	at com.petterp.floatingx.FloatingX.uninstallAll(FloatingX.kt:122)

**Comment by Petterpx** [comment]
更新到2.3.0即可
