### ISSUE TITLE
频繁切换页面，引起黑屏崩溃

### ISSUE THREAD

**Issue by likfe** [Petterpx/FloatingX#36]
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/WindowInsetsCompat$Type;
        at com.petterp.floatingx.impl.control.FxAppControlImpl$windowsInsetsListener$2$1.onApplyWindowInsets(FxAppControlImpl.kt:25)
        at androidx.core.view.ViewCompat$1.onApplyWindowInsets(ViewCompat.java:2474)
        at android.view.View.dispatchApplyWindowInsets(View.java:11469)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7406)
        at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7431)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7413)
        at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2595)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2999)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2252)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8791)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140)
        at android.view.Choreographer.doCallbacks(Choreographer.java:962)
        at android.view.Choreographer.doFrame(Choreographer.java:887)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1125)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8259)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by likfe** [comment]
已定位到原因，可能需要使用 `androidx.core:core:1.5.0` 这个版本才行，出错的版本是 `androidx.core:core:1.3.2`，具体细节应该是 androidx.core 不同版本的 API 差异问题。

**Comment by likfe** [comment]
已定位到详细原因：
```
open class FxAppControlImpl(private val helper: AppHelper) :
    FxBasisControlImpl(helper), IFxAppControl {

    /** 对于状态栏高度的实时监听,在小屏模式下,效果极好 */
    private val windowsInsetsListener by lazyLoad {
        OnApplyWindowInsetsListener { _, insets ->
            val statusBar = insets.getInsets(WindowInsetsCompat.Type.statusBars()).top
            helper.statsBarHeight = statusBar
            helper.fxLog?.v("System--StatusBar---old-(${helper.statsBarHeight}),new-($statusBar))")
            insets
        }
    }
}
```
状态栏监听用到的 `WindowInsetsCompat.Type` 是 [1.5.0-alpha02](https://developer.android.google.cn/jetpack/androidx/releases/core?hl=zh-cn#1.5.0-alpha02) 版本加入的一个类，低于此版本时，会发生 `NoClassDefFoundError` 崩溃。

> 详见
> 将 WindowInsetsCompat 更新为 Android 11 API ([I3df9e](https://android-review.googlesource.com/#/q/I3df9e889650db916c48d5567a9bcf9c7a7b9aa85))

**Comment by likfe** [comment]
个人有个小建议，对于现有项目接入 FloatingX ，较低版本的 androidx.core 可能具有更大的适用性，升级 androidx.core 版本具有不少风险。目前我这边升级后发现了一些常规页面的 UI Bug。

以上仅个人建议。

**Comment by Petterpx** [comment]
androidx.core:core:1.5.0 是appcompat1.3.0附带的包，下个版本会全部移除掉，只保留必需的依赖

**Comment by likfe** [comment]
> androidx.core:core:1.5.0 是appcompat1.3.0附带的包，下个版本会全部移除掉，只保留必需的依赖

辛苦了，非常期待。

**Comment by Petterpx** [comment]
appcompat降级到了1.2，无需手动引入kt和appcompat，修改了依赖方式。

**Comment by Petterpx** [comment]
试试rc14。appcompat降级到了1.2，无需手动引入kt和appcompat，修改了依赖方式。

**Comment by likfe** [comment]
我本地修改的和你 [build:降低appcompat版本到1.2.0](https://github.com/Petterpx/FloatingX/commit/6eb819c05996a6c8ddb27f009b7409f6aa7422f4) 基本一致，哈哈哈，感谢你这么快完成调整。

**Comment by Petterpx** [comment]
没事。感谢反馈😄

**Comment by Petterpx** [comment]
> 我本地修改的和你 [build:降低appcompat版本到1.2.0](https://github.com/Petterpx/FloatingX/commit/6eb819c05996a6c8ddb27f009b7409f6aa7422f4) 基本一致，哈哈哈，感谢你这么快完成调整。

没事。感谢反馈😄
